# Generated by Django 2.2 on 2019-04-26 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_name', models.CharField(max_length=30)),
                ('Company_address', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('University_name', models.CharField(max_length=20)),
                ('University_address', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Universities',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=30)),
                ('m_name', models.CharField(max_length=30)),
                ('l_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('dob', models.DateField()),
                ('height', models.FloatField(max_length=30)),
                ('mob_no', models.IntegerField()),
                ('address', models.CharField(max_length=30)),
                ('m_status', models.CharField(choices=[('y', 'yes'), ('n', 'no')], max_length=1)),
            ],
            options={
                'db_table': 'user',
                'verbose_name_plural': 'User',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.FloatField()),
                ('designation', models.CharField(max_length=30)),
                ('currrently_working', models.BooleanField()),
                ('hire_date', models.DateField()),
                ('end_date', models.DateField()),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_app.Company')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_app.User')),
            ],
            options={
                'verbose_name_plural': 'Experiencies',
            },
        ),
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=20)),
                ('percentage', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('university_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_app.University')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_app.User')),
            ],
            options={
                'verbose_name_plural': 'Academic',
            },
        ),
    ]
