# Generated by Django 2.2 on 2019-04-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='roll_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
